### ISSUE TITLE
OnDecodedData is never triggered

### ISSUE THREAD

**Issue by takazm** [SocketMobile/singleentry-xamarin-android#1]
I ran the sample project and scan the QRCode into the textview  but data is not decoded properly in a multi-line code. I am not sure if this was the intention as the project is called "single entry" i assume that you were expecting one line. The data is read as one long string into the textvew and ignores the newline characters at the end of each line. Since my data is multi-line i expected the OnDecodedData  in the MainActivity to be triggered at some point during the scan but never does. I did notice that the SktScanErrors.SKTSUCCESS(result) in the ScanApiHelper always evaluates to false. Which could explain the reason why the OnDecodedData is never invoked.

Any idea how  we can scan and decode a multi-line code properly

**Comment by EricGlaenzer** [comment]
Hi takazm,
I tried with a multi-line barcode and it works fine. I am attaching the QRCode I used. Can you send yours so we can investigate this issue?
![qrcode multilines](https://cloud.githubusercontent.com/assets/3876881/17174501/015cf942-53d0-11e6-8721-18728cb614d4.png)

**Comment by EricGlaenzer** [comment]
I am closing this issue since we haven't receive any feedback from takazm
