### ISSUE TITLE
Scanner never connects to application.

### ISSUE THREAD

**Issue by carcanoma** [SocketMobile/singleentry-xamarin-android#2]
I have been trying to get the Android implementation of this going for a while now have been unsuccessful. I was able to get the iOS version for xamarin going just fine, but in my application and in the single entry application here, the scanner never connects to the app. I know there was a fix in the other api's concerning marshmallow and Bluetooth pariing and looking at the xamarin sdk, it has not been updated and still in beta since 2015. Is this something that is going to still be supported and worked on? Any ideas why this example never connects running on a device running kit kat?

**Comment by EricGlaenzer** [comment]
Please check out our new Capture SDK.
